---
- name: Update packages
  apt:
    update_cache: yes

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Unarchive the consul binary file
  unarchive:
    src: https://releases.hashicorp.com/consul/0.8.5/consul_0.8.5_linux_amd64.zip
    dest: "{{ binary_path }}"
    remote_src: yes

- name: Create a directory for consul ui
  file:
    path: "{{ ui_path }}"
    state: directory

- name: Unarchive the consul-ui file
  unarchive:
    src: https://releases.hashicorp.com/consul/0.8.5/consul_0.8.5_web_ui.zip
    dest: "{{ ui_path }}"
    remote_src: yes

- name: Generate consul key
  shell: consul keygen
  register: command_output_full

- name: Create config directory
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Copy config file of Consul
  template:
    src: config.json.j2
    dest: "{{ config_dir }}/config.json"

- name: Replace the keygen
  replace: dest="{{ config_dir }}/config.json" regexp='encryption_var' replace={{command_output_full.stdout}}
  tags:
    - red
    
- name: Create a service for Consul
  template:
    src: consul.service_debian.j2
    dest: /etc/systemd/system/consul.service

- name: Reload the daemon
  systemd:
    daemon_reload: yes

- name: Start and enable the service
  systemd:
    name: consul
    state: started
    enabled: yes

